#!/bin/bash
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# Disallow commits on master and development
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ]; then
  echo "Commits on master is not allowed! Only Merges are allowed!"
  exit 1
fi

if [ "$branch" = "development" ]; then
  echo "Commits on development is not allowed! Only Merges are allowed!"
  exit 1
fi

if [ "$branch" = "dev" ]; then
  echo "Commits on dev is not allowed! Only Merges are allowed!"
  exit 1
fi

#Disallow commits if TSLint finds errors
pass=true

#Disallow commits if TSLint finds errors
spin[0]="-"
spin[1]="\\"
spin[2]="|"
spin[3]="/"


# Run tslint and get the output and return code
tslint=$(ng lint) &
pid=$! # Process Id of the previous running command

echo -n "Checking Code Style: ${spin[0]}"
while kill -0 $pid 2>/dev/null
do
    for i  in "${spin[@]}"
    do
        echo -ne "\b$i"
        sleep 0.1
    done
done

echo -ne "\b "

ret_code=$?
# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
		printf "${RED}FAILED:${NC}"
		echo "$tslint"
        exit 1
else
		printf "${GREEN}PASSED:${NC}\n"
		exit 0
fi

